utils: avoid double import and don't append sys.path with same path
sys.path can be populated with same path. Don't append when path is already
added.
ryu-manager --app_lists=ryu/app/rest.py --app_lists=ryu/app/simple_isolation.py
This results that sys.path[-2:] has two same value.
This isn't critical, but annoying when debuging module loading stuff.

Since import_module() isn't aware of cwd, so it may result in double import.
Avoid double import.
In the following example, the first one(ryu.app.event_dumper) imports the
module, ryu.app.event_dumper, relative to ryu/.., the second one
(ryu/app/event_dumper.py) imports the module, event_dumper, relative to
ryu/app. Python thinks that they are different modules.
Although it doesn't make much sense to instantiate same application twice,
I don't think of any reason to prevent it. And it is difficult to understand
what's happening.

> $ PYTHONPATH=$(pwd) ./bin/ryu-manager ryu.app.event_dumper ryu/app/event_dumper.py
> loading app ryu.controller.ofp_handler
> loading app ryu.app.event_dumper
> loading app ./ryu/app/event_dumper.py
> Traceback (most recent call last):
>   File "./bin/ryu-manager", line 81, in <module>
>     main()
>   File "./bin/ryu-manager", line 61, in main
>     app_mgr.load_apps(FLAGS.app_lists)
>   File "/ryu/base/app_manager.py", line 94, in load_apps
>     cls = self.load_app(app_cls_name)
>   File "/ryu/base/app_manager.py", line 74, in load_app
>     mod = utils.import_module(name)
>   File "/ryu/utils.py", line 34, in import_module
>     __import__(name)
>   File "ryu/app/event_dumper.py", line 29, in <module>
>     'list of dispatcher name to dump event: default any')
>   File "/usr/lib/python2.7/dist-packages/gflags.py", line 2673, in DEFINE_multistring
>     DEFINE_multi(parser, serializer, name, default, help, flag_values, **args)
>   File "/usr/lib/python2.7/dist-packages/gflags.py", line 2660, in DEFINE_multi
>     flag_values)
>   File "/usr/lib/python2.7/dist-packages/gflags.py", line 2045, in DEFINE_flag
>     fv[flag.name] = flag
>   File "/usr/lib/python2.7/dist-packages/gflags.py", line 916, in __setitem__
>     raise DuplicateFlagError(name, self)
> gflags.DuplicateFlagError: The flag 'dump_queue' is defined twice. First from ryu.app.event_dumper, Second from event_dumper

Signed-off-by: Isaku Yamahata <yamahata@valinux.co.jp>